-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity toplevel_core_B is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_out_b_0_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    x_out_b_1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    port_current_injection_from_b_to_a_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    port_current_injection_from_b_to_a_V_ap_vld : OUT STD_LOGIC;
    i_in_port_from_a_V : IN STD_LOGIC_VECTOR (71 downto 0);
    V1out_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    V2out_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    I1out_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    I2out_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    I3out_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    Vpout_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    Vsout_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    dac_a_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    dac_a_V_ap_vld : OUT STD_LOGIC;
    dac_b_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    dac_b_V_ap_vld : OUT STD_LOGIC;
    dac_c_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    dac_c_V_ap_vld : OUT STD_LOGIC;
    dac_d_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    dac_d_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of toplevel_core_B is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "toplevel_core_B,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2104-2L-e,HLS_INPUT_CLOCK=70.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=42.261691,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=461,HLS_SYN_FF=522,HLS_SYN_LUT=12630,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_EE : STD_LOGIC_VECTOR (7 downto 0) := "11101110";
    constant ap_const_lv8_77 : STD_LOGIC_VECTOR (7 downto 0) := "01110111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_115 : STD_LOGIC_VECTOR (8 downto 0) := "100010101";
    constant ap_const_lv9_27 : STD_LOGIC_VECTOR (8 downto 0) := "000100111";
    constant ap_const_lv9_9E : STD_LOGIC_VECTOR (8 downto 0) := "010011110";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv109_105D11523F : STD_LOGIC_VECTOR (108 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001000001011101000100010101001000111111";
    constant ap_const_lv88_DB30 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001101101100110000";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv118_33190708F18C : STD_LOGIC_VECTOR (117 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001100110001100100000111000010001111000110001100";
    constant ap_const_lv32_75 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110101";
    constant ap_const_lv46_0 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    constant ap_const_lv47_0 : STD_LOGIC_VECTOR (46 downto 0) := "00000000000000000000000000000000000000000000000";
    constant ap_const_lv104_1CEF684BDA12F60 : STD_LOGIC_VECTOR (103 downto 0) := "00000000000000000000000000000000000000000000000111001110111101101000010010111101101000010010111101100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv60_682AAAAAAAAAAC0 : STD_LOGIC_VECTOR (59 downto 0) := "011010000010101010101010101010101010101010101010101011000000";
    constant ap_const_lv53_B92F684BDA130 : STD_LOGIC_VECTOR (52 downto 0) := "01011100100101111011010000100101111011010000100110000";
    constant ap_const_lv48_400000000000 : STD_LOGIC_VECTOR (47 downto 0) := "010000000000000000000000000000000000000000000000";
    constant ap_const_lv59_1CEF684BDA12F60 : STD_LOGIC_VECTOR (58 downto 0) := "00111001110111101101000010010111101101000010010111101100000";
    constant ap_const_lv48_C00000000000 : STD_LOGIC_VECTOR (47 downto 0) := "110000000000000000000000000000000000000000000000";
    constant ap_const_lv59_0 : STD_LOGIC_VECTOR (58 downto 0) := "00000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv59_631097B425ED0A0 : STD_LOGIC_VECTOR (58 downto 0) := "11000110001000010010111101101000010010111101101000010100000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv60_97D555555555540 : STD_LOGIC_VECTOR (59 downto 0) := "100101111101010101010101010101010101010101010101010101000000";
    constant ap_const_lv53_146D097B425ED0 : STD_LOGIC_VECTOR (52 downto 0) := "10100011011010000100101111011010000100101111011010000";
    constant ap_const_lv131_lc_1 : STD_LOGIC_VECTOR (130 downto 0) := "11111111111111111111111111111111111111111111111111111111111111111111111101101111010100101111011010000100101111011010000100110000000";
    constant ap_const_lv131_lc_2 : STD_LOGIC_VECTOR (130 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010010000101011010000100101111011010000100101111011010000000";
    constant ap_const_lv154_lc_3 : STD_LOGIC_VECTOR (153 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv92_0 : STD_LOGIC_VECTOR (91 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_5C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011100";
    constant ap_const_lv32_A3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100011";
    constant ap_const_lv32_5B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011011";
    constant ap_const_lv140_lc_4 : STD_LOGIC_VECTOR (139 downto 0) := "11111111111111111111111111111111111111111111111111111111111111111111111101011100101011111010101010101010101010101010101010101000000000000000";
    constant ap_const_lv140_lc_5 : STD_LOGIC_VECTOR (139 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010100010110000101010101010101010101010101010101010110000000000000000";
    constant ap_const_lv164_lc_3 : STD_LOGIC_VECTOR (163 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv137_lc_6 : STD_LOGIC_VECTOR (136 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010001011100000100100100100100100100100100100100100101000000000000";
    constant ap_const_lv160_lc_3 : STD_LOGIC_VECTOR (159 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv133_lc_7 : STD_LOGIC_VECTOR (132 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001001000010101101000010010111101101000010010111101101100000000";
    constant ap_const_lv133_lc_8 : STD_LOGIC_VECTOR (132 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001101011110000010010111101101000010010111101101000011000000000";
    constant ap_const_lv157_lc_3 : STD_LOGIC_VECTOR (156 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv119_500000000000 : STD_LOGIC_VECTOR (118 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010100000000000000000000000000000000000000000000";
    constant ap_const_lv98_3594739 : STD_LOGIC_VECTOR (97 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000011010110010100011100111001";
    constant ap_const_lv133_lc_9 : STD_LOGIC_VECTOR (132 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001111111111111110000000000000000000000000000000000000000000000";
    constant ap_const_lv164_lc_10 : STD_LOGIC_VECTOR (163 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001110100100000100010100101101010";
    constant ap_const_lv138_lc_11 : STD_LOGIC_VECTOR (137 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001010";
    constant ap_const_lv32_99 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv173_lc_12 : STD_LOGIC_VECTOR (172 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000100010001000100010001000100010001000";
    constant ap_const_lv32_AC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal counter1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal counter2 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal b_components_V_0 : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal b_components_V_1 : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal V1past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal I1past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal I2past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal I3past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal V2past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln57_fu_360_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln66_fu_396_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_67_fu_1523_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_70_fu_1567_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_26_fu_970_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_36_fu_1121_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_53_fu_1331_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_64_fu_1454_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_44_fu_1232_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln703_2_fu_1579_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln703_3_fu_1596_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_5_fu_512_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_10_fu_577_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal icmp_ln50_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln50_fu_346_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln59_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal nph_fu_382_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln52_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln703_fu_424_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_37_fu_442_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_2_fu_448_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_3_fu_452_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_38_fu_456_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_38_fu_456_p2 : STD_LOGIC_VECTOR (87 downto 0);
    signal r_V_37_fu_442_p2 : STD_LOGIC_VECTOR (108 downto 0);
    signal sext_ln1192_fu_462_p1 : STD_LOGIC_VECTOR (108 downto 0);
    signal ret_V_21_fu_474_p2 : STD_LOGIC_VECTOR (108 downto 0);
    signal tmp_2_fu_480_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln1192_fu_466_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_1_fu_470_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_fu_494_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_3_fu_500_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_fu_508_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_4_fu_490_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_39_fu_519_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_40_fu_525_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_39_fu_519_p2 : STD_LOGIC_VECTOR (87 downto 0);
    signal r_V_40_fu_525_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal sext_ln700_fu_531_p1 : STD_LOGIC_VECTOR (117 downto 0);
    signal ret_V_22_fu_543_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal trunc_ln1192_2_fu_535_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_3_fu_539_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_1_fu_559_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_4_fu_565_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_1_fu_573_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_9_fu_549_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal signbit_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln72_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln78_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal signbit_1_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_11_fu_604_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal p_Val2_14_fu_590_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal p_Val2_15_fu_612_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal zext_ln703_fu_618_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln703_1_fu_622_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_fu_626_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_41_fu_636_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_41_fu_636_p2 : STD_LOGIC_VECTOR (103 downto 0);
    signal tmp_5_fu_642_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_6_fu_656_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln713_fu_652_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln415_2_fu_664_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln130_fu_674_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln130_1_fu_678_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_V_fu_682_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln703_fu_696_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln131_fu_702_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln131_1_fu_706_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_V_5_fu_710_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln703_1_fu_720_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1498_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_17_fu_668_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal icmp_ln1498_2_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1498_1_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln142_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln142_1_fu_752_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal select_ln134_fu_732_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal icmp_ln151_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln147_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln155_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln155_1_fu_786_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal mul_ln703_fu_696_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal icmp_ln164_fu_814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln160_fu_808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_fu_828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln168_1_fu_820_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal mul_ln703_1_fu_720_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln1118_4_fu_846_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_42_fu_850_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_4_fu_846_p1 : STD_LOGIC_VECTOR (130 downto 0);
    signal select_ln142_fu_766_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal sext_ln1118_5_fu_864_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_6_fu_868_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_7_fu_872_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_8_fu_876_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_43_fu_880_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_43_fu_880_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal sext_ln1116_1_fu_856_p1 : STD_LOGIC_VECTOR (129 downto 0);
    signal r_V_43_fu_880_p2 : STD_LOGIC_VECTOR (129 downto 0);
    signal r_V_42_fu_850_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal sext_ln1118_9_fu_886_p1 : STD_LOGIC_VECTOR (130 downto 0);
    signal ret_V_23_fu_890_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal r_V_44_fu_904_p1 : STD_LOGIC_VECTOR (64 downto 0);
    signal r_V_44_fu_904_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal sext_ln1118_11_fu_910_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal sext_ln1193_fu_896_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal ret_V_4_fu_914_p2 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_4_fu_924_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_4_fu_924_p2 : STD_LOGIC_VECTOR (153 downto 0);
    signal lhs_V_fu_934_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln703_5_fu_930_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_fu_934_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_24_fu_942_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_7_fu_958_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_3_fu_966_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_25_fu_948_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal select_ln155_fu_800_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal r_V_45_fu_981_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_45_fu_981_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal r_V_45_fu_981_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal mul_ln1193_fu_991_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln1193_fu_991_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln703_6_fu_987_p1 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln1118_21_fu_1007_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_12_fu_1011_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_13_fu_1015_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_14_fu_1019_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_46_fu_1023_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal ret_V_25_fu_997_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal r_V_46_fu_1023_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln703_8_fu_1033_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal sext_ln703_7_fu_1029_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal sext_ln1118_15_fu_1047_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_16_fu_1051_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_17_fu_1055_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_47_fu_1059_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_47_fu_1059_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln703_9_fu_1065_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal ret_V_26_fu_1037_p2 : STD_LOGIC_VECTOR (140 downto 0);
    signal ret_V_8_fu_1069_p2 : STD_LOGIC_VECTOR (140 downto 0);
    signal r_V_48_fu_1079_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal lhs_V_1_fu_1085_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_48_fu_1079_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_1_fu_1085_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_27_fu_1093_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_8_fu_1109_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_4_fu_1117_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_35_fu_1099_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_19_fu_1132_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_49_fu_1136_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_50_fu_1142_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_50_fu_1142_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal r_V_50_fu_1142_p2 : STD_LOGIC_VECTOR (129 downto 0);
    signal sext_ln1118_27_fu_1148_p1 : STD_LOGIC_VECTOR (130 downto 0);
    signal r_V_49_fu_1136_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal ret_V_28_fu_1152_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal r_V_51_fu_1166_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_51_fu_1166_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal sext_ln1118_28_fu_1172_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal sext_ln1192_2_fu_1158_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal ret_V_11_fu_1176_p2 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_5_fu_1186_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_5_fu_1186_p2 : STD_LOGIC_VECTOR (153 downto 0);
    signal lhs_V_2_fu_1196_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln703_11_fu_1192_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_2_fu_1196_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_29_fu_1204_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_9_fu_1220_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_5_fu_1228_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_43_fu_1210_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_52_fu_1239_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_53_fu_1245_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_52_fu_1239_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal r_V_53_fu_1245_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal sext_ln703_12_fu_1251_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal sext_ln703_13_fu_1255_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal r_V_54_fu_1265_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_54_fu_1265_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal ret_V_30_fu_1259_p2 : STD_LOGIC_VECTOR (137 downto 0);
    signal sext_ln703_14_fu_1271_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal ret_V_14_fu_1275_p2 : STD_LOGIC_VECTOR (137 downto 0);
    signal r_V_55_fu_1285_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal lhs_V_3_fu_1291_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_55_fu_1285_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal sext_ln703_15_fu_1299_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_3_fu_1291_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_31_fu_1303_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_10_fu_1319_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_6_fu_1327_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_52_fu_1309_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_56_fu_1338_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_57_fu_1344_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_56_fu_1338_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_57_fu_1344_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal sext_ln703_16_fu_1350_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal sext_ln703_17_fu_1354_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal r_V_58_fu_1364_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_58_fu_1364_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal ret_V_32_fu_1358_p2 : STD_LOGIC_VECTOR (133 downto 0);
    signal sext_ln703_18_fu_1370_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal select_ln168_fu_834_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln1118_23_fu_1384_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_59_fu_1388_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_59_fu_1388_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal r_V_59_fu_1388_p2 : STD_LOGIC_VECTOR (123 downto 0);
    signal sext_ln703_19_fu_1394_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal ret_V_33_fu_1374_p2 : STD_LOGIC_VECTOR (133 downto 0);
    signal ret_V_18_fu_1398_p2 : STD_LOGIC_VECTOR (133 downto 0);
    signal r_V_60_fu_1408_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal lhs_V_4_fu_1414_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_60_fu_1408_p2 : STD_LOGIC_VECTOR (156 downto 0);
    signal sext_ln703_20_fu_1422_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_4_fu_1414_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_34_fu_1426_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_11_fu_1442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_7_fu_1450_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_63_fu_1432_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_61_fu_1495_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_61_fu_1495_p2 : STD_LOGIC_VECTOR (118 downto 0);
    signal tmp_12_fu_1511_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_8_fu_1519_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_66_fu_1501_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_62_fu_1539_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_62_fu_1539_p2 : STD_LOGIC_VECTOR (118 downto 0);
    signal tmp_13_fu_1555_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_9_fu_1563_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_69_fu_1545_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln703_2_fu_1579_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_V_6_fu_1586_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln703_3_fu_1596_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_V_64_fu_1615_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_64_fu_1615_p2 : STD_LOGIC_VECTOR (97 downto 0);
    signal sext_ln1192_1_fu_1621_p1 : STD_LOGIC_VECTOR (117 downto 0);
    signal r_V_63_fu_1603_p3 : STD_LOGIC_VECTOR (117 downto 0);
    signal ret_V_35_fu_1625_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal tmp_14_fu_1641_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_10_fu_1649_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_74_fu_1631_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_fu_1664_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_fu_1664_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_65_fu_1674_p1 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_65_fu_1674_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal trunc_ln851_fu_1688_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal trunc_ln3_fu_1698_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln851_fu_1692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln851_fu_1708_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_1680_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_fu_1714_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_31_fu_1735_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_31_fu_1735_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_66_fu_1745_p1 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_66_fu_1745_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal trunc_ln851_4_fu_1759_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal trunc_ln851_1_fu_1769_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln851_1_fu_1763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln851_1_fu_1779_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_1_fu_1751_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_1_fu_1785_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_33_fu_1806_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_33_fu_1806_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_67_fu_1816_p1 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_67_fu_1816_p2 : STD_LOGIC_VECTOR (172 downto 0);
    signal trunc_ln851_5_fu_1830_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal trunc_ln851_2_fu_1840_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln851_2_fu_1834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln851_2_fu_1850_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_2_fu_1822_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_2_fu_1856_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_35_fu_1877_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_35_fu_1877_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_68_fu_1887_p1 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_68_fu_1887_p2 : STD_LOGIC_VECTOR (172 downto 0);
    signal trunc_ln851_6_fu_1901_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal trunc_ln851_3_fu_1911_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln851_3_fu_1905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln851_3_fu_1921_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_3_fu_1893_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_3_fu_1927_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                I1past_dab1_V <= p_Val2_36_fu_1121_p2;
                I2past_dab1_V <= p_Val2_53_fu_1331_p2;
                I3past_dab1_V <= p_Val2_64_fu_1454_p2;
                V1past_dab1_V <= p_Val2_26_fu_970_p2;
                V2past_dab1_V <= p_Val2_44_fu_1232_p2;
                b_components_V_0 <= p_Val2_67_fu_1523_p2;
                b_components_V_1 <= p_Val2_70_fu_1567_p2;
                counter1 <= add_ln57_fu_360_p2;
                counter2 <= add_ln66_fu_396_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    I1out_dab1_V <= p_Val2_36_fu_1121_p2;
    I2out_dab1_V <= p_Val2_53_fu_1331_p2;
    I3out_dab1_V <= std_logic_vector(unsigned(zext_ln415_7_fu_1450_p1) + unsigned(p_Val2_63_fu_1432_p4));
    V1out_dab1_V <= p_Val2_26_fu_970_p2;
    V2out_dab1_V <= p_Val2_44_fu_1232_p2;
    Vpout_dab1_V <= mul_ln703_2_fu_1579_p2;
    Vsout_dab1_V <= mul_ln703_3_fu_1596_p2;
    add_ln57_fu_360_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(select_ln50_fu_346_p3));
    add_ln66_fu_396_p2 <= std_logic_vector(unsigned(ap_const_lv9_1) + unsigned(nph_fu_382_p3));
    add_ln703_fu_424_p2 <= std_logic_vector(unsigned(b_components_V_0) + unsigned(i_in_port_from_a_V));
    add_ln713_1_fu_559_p2 <= std_logic_vector(unsigned(trunc_ln1192_2_fu_535_p1) + unsigned(trunc_ln1192_3_fu_539_p1));
    add_ln713_fu_494_p2 <= std_logic_vector(unsigned(trunc_ln1192_fu_466_p1) + unsigned(trunc_ln1192_1_fu_470_p1));
    add_ln851_1_fu_1779_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(trunc_ln851_1_fu_1769_p4));
    add_ln851_2_fu_1850_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(trunc_ln851_2_fu_1840_p4));
    add_ln851_3_fu_1921_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(trunc_ln851_3_fu_1911_p4));
    add_ln851_fu_1708_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(trunc_ln3_fu_1698_p4));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dac_a_V <= 
        select_ln851_fu_1714_p3 when (p_Result_s_fu_1680_p3(0) = '1') else 
        trunc_ln3_fu_1698_p4;

    dac_a_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dac_a_V_ap_vld <= ap_const_logic_1;
        else 
            dac_a_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    dac_b_V <= 
        select_ln851_1_fu_1785_p3 when (p_Result_1_fu_1751_p3(0) = '1') else 
        trunc_ln851_1_fu_1769_p4;

    dac_b_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dac_b_V_ap_vld <= ap_const_logic_1;
        else 
            dac_b_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    dac_c_V <= 
        select_ln851_2_fu_1856_p3 when (p_Result_2_fu_1822_p3(0) = '1') else 
        trunc_ln851_2_fu_1840_p4;

    dac_c_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dac_c_V_ap_vld <= ap_const_logic_1;
        else 
            dac_c_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    dac_d_V <= 
        select_ln851_3_fu_1927_p3 when (p_Result_3_fu_1893_p3(0) = '1') else 
        trunc_ln851_3_fu_1911_p4;

    dac_d_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dac_d_V_ap_vld <= ap_const_logic_1;
        else 
            dac_d_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln147_fu_774_p2 <= "1" when (tmp_V_fu_682_p2 = ap_const_lv2_1) else "0";
    icmp_ln1498_1_fu_740_p2 <= "1" when (ret_V_fu_626_p2 = ap_const_lv48_C00000000000) else "0";
    icmp_ln1498_2_fu_746_p2 <= "1" when (p_Val2_14_fu_590_p3 = p_Val2_11_fu_604_p3) else "0";
    icmp_ln1498_fu_726_p2 <= "1" when (ret_V_fu_626_p2 = ap_const_lv48_400000000000) else "0";
    icmp_ln151_fu_780_p2 <= "1" when (tmp_V_fu_682_p2 = ap_const_lv2_3) else "0";
    icmp_ln160_fu_808_p2 <= "1" when (tmp_V_5_fu_710_p2 = ap_const_lv2_1) else "0";
    icmp_ln164_fu_814_p2 <= "1" when (tmp_V_5_fu_710_p2 = ap_const_lv2_3) else "0";
    icmp_ln50_fu_340_p2 <= "1" when (unsigned(counter1) < unsigned(ap_const_lv8_EE)) else "0";
    icmp_ln52_fu_354_p2 <= "1" when (unsigned(select_ln50_fu_346_p3) < unsigned(ap_const_lv8_77)) else "0";
    icmp_ln59_fu_376_p2 <= "1" when (unsigned(counter2) < unsigned(ap_const_lv9_115)) else "0";
    icmp_ln61_fu_390_p2 <= "1" when (unsigned(nph_fu_382_p3) < unsigned(ap_const_lv9_9E)) else "0";
    icmp_ln851_1_fu_1763_p2 <= "1" when (trunc_ln851_4_fu_1759_p1 = ap_const_lv138_lc_11) else "0";
    icmp_ln851_2_fu_1834_p2 <= "1" when (trunc_ln851_5_fu_1830_p1 = ap_const_lv138_lc_11) else "0";
    icmp_ln851_3_fu_1905_p2 <= "1" when (trunc_ln851_6_fu_1901_p1 = ap_const_lv138_lc_11) else "0";
    icmp_ln851_fu_1692_p2 <= "1" when (trunc_ln851_fu_1688_p1 = ap_const_lv138_lc_11) else "0";
    lhs_V_1_fu_1085_p1 <= I1past_dab1_V;
    lhs_V_1_fu_1085_p3 <= (lhs_V_1_fu_1085_p1 & ap_const_lv92_0);
    lhs_V_2_fu_1196_p1 <= V2past_dab1_V;
    lhs_V_2_fu_1196_p3 <= (lhs_V_2_fu_1196_p1 & ap_const_lv92_0);
    lhs_V_3_fu_1291_p1 <= I2past_dab1_V;
    lhs_V_3_fu_1291_p3 <= (lhs_V_3_fu_1291_p1 & ap_const_lv92_0);
    lhs_V_4_fu_1414_p1 <= I3past_dab1_V;
    lhs_V_4_fu_1414_p3 <= (lhs_V_4_fu_1414_p1 & ap_const_lv92_0);
    lhs_V_fu_934_p1 <= V1past_dab1_V;
    lhs_V_fu_934_p3 <= (lhs_V_fu_934_p1 & ap_const_lv92_0);
    mul_ln1193_fu_991_p1 <= sext_ln1118_8_fu_876_p0;
    mul_ln1193_fu_991_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ap_const_lv140_lc_4) * signed(mul_ln1193_fu_991_p1))), 140));
    mul_ln703_1_fu_720_p1 <= tmp_V_5_fu_710_p2;
    mul_ln703_1_fu_720_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv53_B92F684BDA130) * signed(mul_ln703_1_fu_720_p1))), 53));
    mul_ln703_2_fu_1579_p0 <= tmp_V_fu_682_p2;
    mul_ln703_2_fu_1579_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln703_2_fu_1579_p0) * signed(p_Val2_26_fu_970_p2))), 72));
    mul_ln703_3_fu_1596_p0 <= tmp_V_6_fu_1586_p2;
    mul_ln703_3_fu_1596_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln703_3_fu_1596_p0) * signed(p_Val2_44_fu_1232_p2))), 72));
    mul_ln703_4_fu_924_p1 <= ret_V_4_fu_914_p2;
    mul_ln703_4_fu_924_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv154_lc_3) * signed(mul_ln703_4_fu_924_p1))), 154));
    mul_ln703_5_fu_1186_p1 <= ret_V_11_fu_1176_p2;
    mul_ln703_5_fu_1186_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv154_lc_3) * signed(mul_ln703_5_fu_1186_p1))), 154));
    mul_ln703_fu_696_p1 <= tmp_V_fu_682_p2;
    mul_ln703_fu_696_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv60_682AAAAAAAAAAC0) * signed(mul_ln703_fu_696_p1))), 60));
    nph_fu_382_p3 <= 
        counter2 when (icmp_ln59_fu_376_p2(0) = '1') else 
        ap_const_lv9_27;
    or_ln142_fu_760_p2 <= (icmp_ln1498_2_fu_746_p2 or icmp_ln1498_1_fu_740_p2);
    or_ln155_fu_794_p2 <= (icmp_ln151_fu_780_p2 or icmp_ln147_fu_774_p2);
    or_ln168_fu_828_p2 <= (icmp_ln164_fu_814_p2 or icmp_ln160_fu_808_p2);
    p_Result_1_fu_1751_p3 <= r_V_66_fu_1745_p2(163 downto 163);
    p_Result_2_fu_1822_p3 <= r_V_67_fu_1816_p2(172 downto 172);
    p_Result_3_fu_1893_p3 <= r_V_68_fu_1887_p2(172 downto 172);
    p_Result_s_fu_1680_p3 <= r_V_65_fu_1674_p2(163 downto 163);
    p_Val2_10_fu_577_p2 <= std_logic_vector(unsigned(zext_ln415_1_fu_573_p1) + unsigned(p_Val2_9_fu_549_p4));
    p_Val2_11_fu_604_p3 <= (signbit_1_fu_598_p2 & ap_const_lv46_0);
    p_Val2_14_fu_590_p3 <= (signbit_fu_584_p2 & ap_const_lv46_0);
    p_Val2_15_fu_612_p2 <= std_logic_vector(unsigned(ap_const_lv47_0) - unsigned(p_Val2_11_fu_604_p3));
    p_Val2_17_fu_668_p2 <= std_logic_vector(signed(sext_ln713_fu_652_p1) + signed(zext_ln415_2_fu_664_p1));
    p_Val2_25_fu_948_p4 <= ret_V_24_fu_942_p2(163 downto 92);
    p_Val2_26_fu_970_p2 <= std_logic_vector(unsigned(zext_ln415_3_fu_966_p1) + unsigned(p_Val2_25_fu_948_p4));
    p_Val2_35_fu_1099_p4 <= ret_V_27_fu_1093_p2(163 downto 92);
    p_Val2_36_fu_1121_p2 <= std_logic_vector(unsigned(zext_ln415_4_fu_1117_p1) + unsigned(p_Val2_35_fu_1099_p4));
    p_Val2_43_fu_1210_p4 <= ret_V_29_fu_1204_p2(163 downto 92);
    p_Val2_44_fu_1232_p2 <= std_logic_vector(unsigned(zext_ln415_5_fu_1228_p1) + unsigned(p_Val2_43_fu_1210_p4));
        p_Val2_4_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_480_p4),72));

    p_Val2_52_fu_1309_p4 <= ret_V_31_fu_1303_p2(163 downto 92);
    p_Val2_53_fu_1331_p2 <= std_logic_vector(unsigned(zext_ln415_6_fu_1327_p1) + unsigned(p_Val2_52_fu_1309_p4));
    p_Val2_5_fu_512_p2 <= std_logic_vector(unsigned(zext_ln415_fu_508_p1) + unsigned(p_Val2_4_fu_490_p1));
    p_Val2_63_fu_1432_p4 <= ret_V_34_fu_1426_p2(163 downto 92);
    p_Val2_64_fu_1454_p2 <= std_logic_vector(unsigned(zext_ln415_7_fu_1450_p1) + unsigned(p_Val2_63_fu_1432_p4));
    p_Val2_66_fu_1501_p4 <= r_V_61_fu_1495_p2(117 downto 46);
    p_Val2_67_fu_1523_p2 <= std_logic_vector(unsigned(zext_ln415_8_fu_1519_p1) + unsigned(p_Val2_66_fu_1501_p4));
    p_Val2_69_fu_1545_p4 <= r_V_62_fu_1539_p2(117 downto 46);
    p_Val2_70_fu_1567_p2 <= std_logic_vector(unsigned(zext_ln415_9_fu_1563_p1) + unsigned(p_Val2_69_fu_1545_p4));
    p_Val2_74_fu_1631_p4 <= ret_V_35_fu_1625_p2(117 downto 46);
    p_Val2_9_fu_549_p4 <= ret_V_22_fu_543_p2(117 downto 46);
    port_current_injection_from_b_to_a_V <= std_logic_vector(unsigned(zext_ln415_10_fu_1649_p1) + unsigned(p_Val2_74_fu_1631_p4));

    port_current_injection_from_b_to_a_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            port_current_injection_from_b_to_a_V_ap_vld <= ap_const_logic_1;
        else 
            port_current_injection_from_b_to_a_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_V_31_fu_1735_p1 <= mul_ln703_3_fu_1596_p2;
    r_V_31_fu_1735_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_9) * signed(r_V_31_fu_1735_p1))), 133));
    r_V_33_fu_1806_p1 <= p_Val2_36_fu_1121_p2;
    r_V_33_fu_1806_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_9) * signed(r_V_33_fu_1806_p1))), 133));
    r_V_35_fu_1877_p1 <= p_Val2_53_fu_1331_p2;
    r_V_35_fu_1877_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_9) * signed(r_V_35_fu_1877_p1))), 133));
    r_V_37_fu_442_p1 <= add_ln703_fu_424_p2;
    r_V_37_fu_442_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv109_105D11523F) * signed(r_V_37_fu_442_p1))), 109));
    r_V_38_fu_456_p1 <= sext_ln1118_3_fu_452_p0;
    r_V_38_fu_456_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv88_DB30) * signed(r_V_38_fu_456_p1))), 88));
    r_V_39_fu_519_p1 <= add_ln703_fu_424_p2;
    r_V_39_fu_519_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv88_DB30) * signed(r_V_39_fu_519_p1))), 88));
    r_V_40_fu_525_p1 <= sext_ln1118_2_fu_448_p0;
    r_V_40_fu_525_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv118_33190708F18C) * signed(r_V_40_fu_525_p1))), 118));
    r_V_41_fu_636_p1 <= ret_V_fu_626_p2;
    r_V_41_fu_636_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv104_1CEF684BDA12F60) * signed(r_V_41_fu_636_p1))), 104));
    r_V_42_fu_850_p1 <= sext_ln1118_4_fu_846_p1(72 - 1 downto 0);
    r_V_42_fu_850_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ap_const_lv131_lc_1) * signed(r_V_42_fu_850_p1))), 131));
    r_V_43_fu_880_p0 <= sext_ln1118_5_fu_864_p0;
    r_V_43_fu_880_p1 <= sext_ln1116_1_fu_856_p1(59 - 1 downto 0);
    r_V_43_fu_880_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_43_fu_880_p0) * signed(r_V_43_fu_880_p1))), 130));
    r_V_44_fu_904_p1 <= p_Val2_5_fu_512_p2(65 - 1 downto 0);
    r_V_44_fu_904_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv131_lc_2) * signed(r_V_44_fu_904_p1))), 131));
    r_V_45_fu_981_p0 <= sext_ln1118_4_fu_846_p1(72 - 1 downto 0);
    r_V_45_fu_981_p1 <= select_ln155_fu_800_p3;
    r_V_45_fu_981_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_45_fu_981_p0) * signed(r_V_45_fu_981_p1))), 131));
    r_V_46_fu_1023_p1 <= sext_ln1118_14_fu_1019_p0;
    r_V_46_fu_1023_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv140_lc_5) * signed(r_V_46_fu_1023_p1))), 140));
    r_V_47_fu_1059_p1 <= sext_ln1118_17_fu_1055_p0;
    r_V_47_fu_1059_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv140_lc_5) * signed(r_V_47_fu_1059_p1))), 140));
    r_V_48_fu_1079_p1 <= ret_V_8_fu_1069_p2;
    r_V_48_fu_1079_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv164_lc_3) * signed(r_V_48_fu_1079_p1))), 164));
    r_V_49_fu_1136_p1 <= sext_ln1118_19_fu_1132_p0;
    r_V_49_fu_1136_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ap_const_lv131_lc_1) * signed(r_V_49_fu_1136_p1))), 131));
    r_V_50_fu_1142_p0 <= sext_ln1118_21_fu_1007_p0;
    r_V_50_fu_1142_p1 <= sext_ln1116_1_fu_856_p1(59 - 1 downto 0);
    r_V_50_fu_1142_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_50_fu_1142_p0) * signed(r_V_50_fu_1142_p1))), 130));
    r_V_51_fu_1166_p1 <= p_Val2_10_fu_577_p2;
    r_V_51_fu_1166_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv131_lc_2) * signed(r_V_51_fu_1166_p1))), 131));
    r_V_52_fu_1239_p1 <= sext_ln1118_7_fu_872_p0;
    r_V_52_fu_1239_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv137_lc_6) * signed(r_V_52_fu_1239_p1))), 137));
    r_V_53_fu_1245_p1 <= sext_ln1118_13_fu_1015_p0;
    r_V_53_fu_1245_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv137_lc_6) * signed(r_V_53_fu_1245_p1))), 137));
    r_V_54_fu_1265_p1 <= sext_ln1118_16_fu_1051_p0;
    r_V_54_fu_1265_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv137_lc_6) * signed(r_V_54_fu_1265_p1))), 137));
    r_V_55_fu_1285_p1 <= ret_V_14_fu_1275_p2;
    r_V_55_fu_1285_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv160_lc_3) * signed(r_V_55_fu_1285_p1))), 160));
    r_V_56_fu_1338_p1 <= sext_ln1118_6_fu_868_p0;
    r_V_56_fu_1338_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_7) * signed(r_V_56_fu_1338_p1))), 133));
    r_V_57_fu_1344_p1 <= sext_ln1118_12_fu_1011_p0;
    r_V_57_fu_1344_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_7) * signed(r_V_57_fu_1344_p1))), 133));
    r_V_58_fu_1364_p1 <= sext_ln1118_15_fu_1047_p0;
    r_V_58_fu_1364_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_8) * signed(r_V_58_fu_1364_p1))), 133));
    r_V_59_fu_1388_p0 <= sext_ln1118_23_fu_1384_p0;
    r_V_59_fu_1388_p1 <= select_ln168_fu_834_p3;
    r_V_59_fu_1388_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_59_fu_1388_p0) * signed(r_V_59_fu_1388_p1))), 124));
    r_V_60_fu_1408_p1 <= ret_V_18_fu_1398_p2;
    r_V_60_fu_1408_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv157_lc_3) * signed(r_V_60_fu_1408_p1))), 157));
    r_V_61_fu_1495_p1 <= p_Val2_26_fu_970_p2;
    r_V_61_fu_1495_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv119_500000000000) * signed(r_V_61_fu_1495_p1))), 119));
    r_V_62_fu_1539_p1 <= p_Val2_44_fu_1232_p2;
    r_V_62_fu_1539_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv119_500000000000) * signed(r_V_62_fu_1539_p1))), 119));
    r_V_63_fu_1603_p3 <= (p_Val2_67_fu_1523_p2 & ap_const_lv46_0);
    r_V_64_fu_1615_p1 <= p_Val2_70_fu_1567_p2;
    r_V_64_fu_1615_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv98_3594739) * signed(r_V_64_fu_1615_p1))), 98));
    r_V_65_fu_1674_p1 <= r_V_fu_1664_p2;
    r_V_65_fu_1674_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv164_lc_10) * signed(r_V_65_fu_1674_p1))), 164));
    r_V_66_fu_1745_p1 <= r_V_31_fu_1735_p2;
    r_V_66_fu_1745_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv164_lc_10) * signed(r_V_66_fu_1745_p1))), 164));
    r_V_67_fu_1816_p1 <= r_V_33_fu_1806_p2;
    r_V_67_fu_1816_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv173_lc_12) * signed(r_V_67_fu_1816_p1))), 173));
    r_V_68_fu_1887_p1 <= r_V_35_fu_1877_p2;
    r_V_68_fu_1887_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv173_lc_12) * signed(r_V_68_fu_1887_p1))), 173));
    r_V_fu_1664_p1 <= mul_ln703_2_fu_1579_p2;
    r_V_fu_1664_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_9) * signed(r_V_fu_1664_p1))), 133));
    ret_V_11_fu_1176_p2 <= std_logic_vector(signed(sext_ln1118_28_fu_1172_p1) + signed(sext_ln1192_2_fu_1158_p1));
    ret_V_14_fu_1275_p2 <= std_logic_vector(unsigned(ret_V_30_fu_1259_p2) - unsigned(sext_ln703_14_fu_1271_p1));
    ret_V_18_fu_1398_p2 <= std_logic_vector(signed(sext_ln703_19_fu_1394_p1) + signed(ret_V_33_fu_1374_p2));
    ret_V_21_fu_474_p2 <= std_logic_vector(signed(sext_ln1192_fu_462_p1) + signed(r_V_37_fu_442_p2));
    ret_V_22_fu_543_p2 <= std_logic_vector(unsigned(r_V_40_fu_525_p2) + unsigned(sext_ln700_fu_531_p1));
    ret_V_23_fu_890_p2 <= std_logic_vector(unsigned(r_V_42_fu_850_p2) - unsigned(sext_ln1118_9_fu_886_p1));
    ret_V_24_fu_942_p2 <= std_logic_vector(signed(sext_ln703_5_fu_930_p1) + signed(lhs_V_fu_934_p3));
    ret_V_25_fu_997_p2 <= std_logic_vector(unsigned(mul_ln1193_fu_991_p2) + unsigned(sext_ln703_6_fu_987_p1));
    ret_V_26_fu_1037_p2 <= std_logic_vector(signed(sext_ln703_8_fu_1033_p1) + signed(sext_ln703_7_fu_1029_p1));
    ret_V_27_fu_1093_p2 <= std_logic_vector(unsigned(r_V_48_fu_1079_p2) + unsigned(lhs_V_1_fu_1085_p3));
    ret_V_28_fu_1152_p2 <= std_logic_vector(signed(sext_ln1118_27_fu_1148_p1) + signed(r_V_49_fu_1136_p2));
    ret_V_29_fu_1204_p2 <= std_logic_vector(signed(sext_ln703_11_fu_1192_p1) + signed(lhs_V_2_fu_1196_p3));
    ret_V_30_fu_1259_p2 <= std_logic_vector(signed(sext_ln703_12_fu_1251_p1) - signed(sext_ln703_13_fu_1255_p1));
    ret_V_31_fu_1303_p2 <= std_logic_vector(signed(sext_ln703_15_fu_1299_p1) + signed(lhs_V_3_fu_1291_p3));
    ret_V_32_fu_1358_p2 <= std_logic_vector(signed(sext_ln703_16_fu_1350_p1) - signed(sext_ln703_17_fu_1354_p1));
    ret_V_33_fu_1374_p2 <= std_logic_vector(unsigned(ret_V_32_fu_1358_p2) - unsigned(sext_ln703_18_fu_1370_p1));
    ret_V_34_fu_1426_p2 <= std_logic_vector(signed(sext_ln703_20_fu_1422_p1) + signed(lhs_V_4_fu_1414_p3));
    ret_V_35_fu_1625_p2 <= std_logic_vector(signed(sext_ln1192_1_fu_1621_p1) + signed(r_V_63_fu_1603_p3));
    ret_V_4_fu_914_p2 <= std_logic_vector(signed(sext_ln1118_11_fu_910_p1) + signed(sext_ln1193_fu_896_p1));
    ret_V_8_fu_1069_p2 <= std_logic_vector(signed(sext_ln703_9_fu_1065_p1) + signed(ret_V_26_fu_1037_p2));
    ret_V_fu_626_p2 <= std_logic_vector(unsigned(zext_ln703_fu_618_p1) + unsigned(sext_ln703_1_fu_622_p1));
    select_ln134_fu_732_p3 <= 
        ap_const_lv59_1CEF684BDA12F60 when (icmp_ln1498_fu_726_p2(0) = '1') else 
        p_Val2_17_fu_668_p2;
    select_ln142_1_fu_752_p3 <= 
        ap_const_lv59_0 when (icmp_ln1498_2_fu_746_p2(0) = '1') else 
        ap_const_lv59_631097B425ED0A0;
    select_ln142_fu_766_p3 <= 
        select_ln142_1_fu_752_p3 when (or_ln142_fu_760_p2(0) = '1') else 
        select_ln134_fu_732_p3;
    select_ln155_1_fu_786_p3 <= 
        ap_const_lv60_97D555555555540 when (icmp_ln151_fu_780_p2(0) = '1') else 
        ap_const_lv60_682AAAAAAAAAAC0;
    select_ln155_fu_800_p3 <= 
        select_ln155_1_fu_786_p3 when (or_ln155_fu_794_p2(0) = '1') else 
        mul_ln703_fu_696_p2;
    select_ln168_1_fu_820_p3 <= 
        ap_const_lv53_146D097B425ED0 when (icmp_ln164_fu_814_p2(0) = '1') else 
        ap_const_lv53_B92F684BDA130;
    select_ln168_fu_834_p3 <= 
        select_ln168_1_fu_820_p3 when (or_ln168_fu_828_p2(0) = '1') else 
        mul_ln703_1_fu_720_p2;
    select_ln50_fu_346_p3 <= 
        counter1 when (icmp_ln50_fu_340_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln851_1_fu_1785_p3 <= 
        trunc_ln851_1_fu_1769_p4 when (icmp_ln851_1_fu_1763_p2(0) = '1') else 
        add_ln851_1_fu_1779_p2;
    select_ln851_2_fu_1856_p3 <= 
        trunc_ln851_2_fu_1840_p4 when (icmp_ln851_2_fu_1834_p2(0) = '1') else 
        add_ln851_2_fu_1850_p2;
    select_ln851_3_fu_1927_p3 <= 
        trunc_ln851_3_fu_1911_p4 when (icmp_ln851_3_fu_1905_p2(0) = '1') else 
        add_ln851_3_fu_1921_p2;
    select_ln851_fu_1714_p3 <= 
        trunc_ln3_fu_1698_p4 when (icmp_ln851_fu_1692_p2(0) = '1') else 
        add_ln851_fu_1708_p2;
        sext_ln1116_1_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln142_fu_766_p3),130));

        sext_ln1118_11_fu_910_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_44_fu_904_p2),132));

    sext_ln1118_12_fu_1011_p0 <= I2past_dab1_V;
    sext_ln1118_13_fu_1015_p0 <= I2past_dab1_V;
    sext_ln1118_14_fu_1019_p0 <= I2past_dab1_V;
    sext_ln1118_15_fu_1047_p0 <= I3past_dab1_V;
    sext_ln1118_16_fu_1051_p0 <= I3past_dab1_V;
    sext_ln1118_17_fu_1055_p0 <= I3past_dab1_V;
    sext_ln1118_19_fu_1132_p0 <= V2past_dab1_V;
    sext_ln1118_21_fu_1007_p0 <= I2past_dab1_V;
    sext_ln1118_23_fu_1384_p0 <= V2past_dab1_V;
        sext_ln1118_27_fu_1148_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_50_fu_1142_p2),131));

        sext_ln1118_28_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_51_fu_1166_p2),132));

    sext_ln1118_2_fu_448_p0 <= b_components_V_1;
    sext_ln1118_3_fu_452_p0 <= b_components_V_1;
    sext_ln1118_4_fu_846_p0 <= V1past_dab1_V;
        sext_ln1118_4_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_4_fu_846_p0),131));

    sext_ln1118_5_fu_864_p0 <= I1past_dab1_V;
    sext_ln1118_6_fu_868_p0 <= I1past_dab1_V;
    sext_ln1118_7_fu_872_p0 <= I1past_dab1_V;
    sext_ln1118_8_fu_876_p0 <= I1past_dab1_V;
        sext_ln1118_9_fu_886_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_43_fu_880_p2),131));

        sext_ln1192_1_fu_1621_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_64_fu_1615_p2),118));

        sext_ln1192_2_fu_1158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_28_fu_1152_p2),132));

        sext_ln1192_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_38_fu_456_p2),109));

        sext_ln1193_fu_896_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_23_fu_890_p2),132));

        sext_ln700_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_39_fu_519_p2),118));

        sext_ln703_11_fu_1192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln703_5_fu_1186_p2),164));

        sext_ln703_12_fu_1251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_52_fu_1239_p2),138));

        sext_ln703_13_fu_1255_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_53_fu_1245_p2),138));

        sext_ln703_14_fu_1271_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_54_fu_1265_p2),138));

        sext_ln703_15_fu_1299_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_55_fu_1285_p2),164));

        sext_ln703_16_fu_1350_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_56_fu_1338_p2),134));

        sext_ln703_17_fu_1354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_57_fu_1344_p2),134));

        sext_ln703_18_fu_1370_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_58_fu_1364_p2),134));

        sext_ln703_19_fu_1394_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_59_fu_1388_p2),134));

        sext_ln703_1_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_15_fu_612_p2),48));

        sext_ln703_20_fu_1422_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_60_fu_1408_p2),164));

        sext_ln703_5_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln703_4_fu_924_p2),164));

        sext_ln703_6_fu_987_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_45_fu_981_p2),140));

        sext_ln703_7_fu_1029_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_25_fu_997_p2),141));

        sext_ln703_8_fu_1033_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_46_fu_1023_p2),141));

        sext_ln703_9_fu_1065_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_47_fu_1059_p2),141));

        sext_ln713_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_642_p4),59));

    signbit_1_fu_598_p2 <= (xor_ln78_fu_414_p2 and xor_ln72_fu_408_p2);
    signbit_fu_584_p2 <= (icmp_ln61_fu_390_p2 and icmp_ln52_fu_354_p2);
    tmp_10_fu_1319_p3 <= r_V_55_fu_1285_p2(91 downto 91);
    tmp_11_fu_1442_p3 <= r_V_60_fu_1408_p2(91 downto 91);
    tmp_12_fu_1511_p3 <= r_V_61_fu_1495_p2(45 downto 45);
    tmp_13_fu_1555_p3 <= r_V_62_fu_1539_p2(45 downto 45);
    tmp_14_fu_1641_p3 <= r_V_64_fu_1615_p2(45 downto 45);
    tmp_2_fu_480_p4 <= ret_V_21_fu_474_p2(108 downto 46);
    tmp_3_fu_500_p3 <= add_ln713_fu_494_p2(45 downto 45);
    tmp_4_fu_565_p3 <= add_ln713_1_fu_559_p2(45 downto 45);
    tmp_5_fu_642_p4 <= r_V_41_fu_636_p2(103 downto 46);
    tmp_6_fu_656_p3 <= r_V_41_fu_636_p2(45 downto 45);
    tmp_7_fu_958_p3 <= ret_V_24_fu_942_p2(91 downto 91);
    tmp_8_fu_1109_p3 <= ret_V_27_fu_1093_p2(91 downto 91);
    tmp_9_fu_1220_p3 <= ret_V_29_fu_1204_p2(91 downto 91);
    tmp_V_5_fu_710_p2 <= std_logic_vector(unsigned(zext_ln131_fu_702_p1) - unsigned(zext_ln131_1_fu_706_p1));
    tmp_V_6_fu_1586_p2 <= std_logic_vector(unsigned(zext_ln131_1_fu_706_p1) - unsigned(zext_ln131_fu_702_p1));
    tmp_V_fu_682_p2 <= std_logic_vector(unsigned(zext_ln130_fu_674_p1) - unsigned(zext_ln130_1_fu_678_p1));
    trunc_ln1192_1_fu_470_p1 <= r_V_38_fu_456_p2(46 - 1 downto 0);
    trunc_ln1192_2_fu_535_p1 <= r_V_39_fu_519_p2(46 - 1 downto 0);
    trunc_ln1192_3_fu_539_p1 <= r_V_40_fu_525_p2(46 - 1 downto 0);
    trunc_ln1192_fu_466_p1 <= r_V_37_fu_442_p2(46 - 1 downto 0);
    trunc_ln3_fu_1698_p4 <= r_V_65_fu_1674_p2(153 downto 138);
    trunc_ln851_1_fu_1769_p4 <= r_V_66_fu_1745_p2(153 downto 138);
    trunc_ln851_2_fu_1840_p4 <= r_V_67_fu_1816_p2(153 downto 138);
    trunc_ln851_3_fu_1911_p4 <= r_V_68_fu_1887_p2(153 downto 138);
    trunc_ln851_4_fu_1759_p1 <= r_V_66_fu_1745_p2(138 - 1 downto 0);
    trunc_ln851_5_fu_1830_p1 <= r_V_67_fu_1816_p2(138 - 1 downto 0);
    trunc_ln851_6_fu_1901_p1 <= r_V_68_fu_1887_p2(138 - 1 downto 0);
    trunc_ln851_fu_1688_p1 <= r_V_65_fu_1674_p2(138 - 1 downto 0);
    x_out_b_0_V <= p_Val2_5_fu_512_p2;
    x_out_b_1_V <= p_Val2_10_fu_577_p2;
    xor_ln72_fu_408_p2 <= (icmp_ln52_fu_354_p2 xor ap_const_lv1_1);
    xor_ln78_fu_414_p2 <= (icmp_ln61_fu_390_p2 xor ap_const_lv1_1);
    zext_ln130_1_fu_678_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln72_fu_408_p2),2));
    zext_ln130_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln52_fu_354_p2),2));
    zext_ln131_1_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln61_fu_390_p2),2));
    zext_ln131_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln78_fu_414_p2),2));
    zext_ln415_10_fu_1649_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_1641_p3),72));
    zext_ln415_1_fu_573_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_565_p3),72));
    zext_ln415_2_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_656_p3),59));
    zext_ln415_3_fu_966_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_958_p3),72));
    zext_ln415_4_fu_1117_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_1109_p3),72));
    zext_ln415_5_fu_1228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_1220_p3),72));
    zext_ln415_6_fu_1327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_1319_p3),72));
    zext_ln415_7_fu_1450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_1442_p3),72));
    zext_ln415_8_fu_1519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_1511_p3),72));
    zext_ln415_9_fu_1563_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_1555_p3),72));
    zext_ln415_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_500_p3),72));
    zext_ln703_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_14_fu_590_p3),48));
end behav;
